DB_CONNECTION_STRING = "mongodb+srv://LLMDB:8cC2kYJRZd10slp0@modellingvistic.u7oxgvf.mongodb.net/"
Environment = "Dev"
AccountCollection = "AccountsCollection"
TranslationCollection = "TranslationsCollection"
TranslatedEntryCollection = "TranslatedEntriesCollection"
